### ISSUE TITLE
Dark theme examples not showing correctly on /themes

### ISSUE THREAD

**Issue by healeycodes** [stork-search/site#34]
Looks like the theme previews for Dark and Edible Dark aren't displaying correctly. It looks like all the examples are light mode.

Chrome `Version 96.0.4664.110 (Official Build) (arm64)`

e.g. here's Edible Dark on https://stork-search.net/themes

<img width="782" alt="Edible Dark displays without a dark theme on /themes" src="https://user-images.githubusercontent.com/34559231/149827550-d35ee711-491d-4f27-b66f-5d0e733d6718.png">

**Comment by jameslittle230** [comment]
Thanks for reporting - fix is going out now. :)
